//
//  RegistrationView.h
//  Lifester
//
//  Created by App Developer on 28/01/13.
//  Copyright (c) 2013 App Developer. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "AppDelegate.h"
#import <MapKit/MapKit.h>
#import <CoreLocation/CoreLocation.h>
#import "TDDatePickerController.h"
#import "TPKeyboardAvoidingScrollView.h"

@class CategoryView;

@interface RegistrationView : UIViewController < UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIActionSheetDelegate, MKMapViewDelegate, CLLocationManagerDelegate, UIScrollViewDelegate, UIWebViewDelegate > {
    
    IBOutlet UILabel *headLbl;
    IBOutlet UIToolbar *toolbar;
    IBOutlet UITextField *fname,*lname,*dob,*sex;
    AppDelegate *appDelegateObj;
    
    IBOutlet UIView *errorOverlay;
    IBOutlet UIView *usernameView;
    IBOutlet UIView *phoneView;
    IBOutlet UIView *emailView;
    IBOutlet UIView *passwordView;
    IBOutlet UIButton *btnUsernameAccesary;
    IBOutlet UIButton *btnSignIn;
    
    UIImagePickerController * imagePicker;
    IBOutlet UIImageView *imageView;
    UIButton *btnCancel;
    UIButton *btnWebviewCancel;
    BOOL isUpload,isFrameExtended;
    
    UIView *pickerViewPopup;
    UIDatePicker *pickerView;
    CLLocationManager *locationManager;
    CLLocationCoordinate2D currentCentre;
    IBOutlet UIView *innerView;
    IBOutlet TPKeyboardAvoidingScrollView *scroller;
    IBOutlet UIView *backgroundView;
    IBOutlet UIView *backgroundView1;
    TDDatePickerController *picker;

    IBOutlet UITextField *txtUsername;
    IBOutlet UITextField *txtprofilename;
//    IBOutlet UITextField *txtLastname;
    IBOutlet UITextField *txtPhoneNumber;
    IBOutlet UITextField *txtEmail;
    IBOutlet UITextField *txtConfirmEmail;
    IBOutlet UITextField *txtPassword;
    
    NSString *city, *state, *country;
    NSString *quesId;
    NSMutableArray *QuesArr;
    
    BOOL isUsernameAutoGenerated;
    IBOutlet UIView *overLayViewInfo;
    int flag;
    IBOutlet UIView *PrivacyView;
    IBOutlet UIWebView *webView;
    IBOutlet UILabel *WebHeadLbl;
    IBOutlet UIActivityIndicatorView *actind;
}
@property (nonatomic, retain) NSString *city, *state, *country;
@property (nonatomic, retain) UIButton *btnCancel, *btnWebviewCancel;
@property (nonatomic, retain) UITextField *txtprofilename;

-(IBAction)BackBtnCall;
-(void)hideKeyboard;

- (IBAction)SelectImage:(id)sender;
- (IBAction)onKeyReturn:(id)sender;
- (IBAction)btnConfirm:(id)sender;
- (IBAction)btnSignupAction:(id)sender;
- (IBAction)btnHideConfirmEmailOverlayAction:(id)sender;
- (IBAction)SignUpWithFacebook:(id)sender;

@end
