//
//  UsernameViewController.h
//  Lifester
//
//  Created by MAC240 on 2/4/14.
//  Copyright (c) 2014 App Developer. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "ASIFormDataRequest.h"
#import "AppDelegate.h"

@interface UsernameViewController : UIViewController <UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIActionSheetDelegate>
{
    IBOutlet UIImageView *imvProfile;
    IBOutlet UITextField *txtProfileName;
    IBOutlet UITextField *txtUsername;
    IBOutlet UIView *usernameView;
    IBOutlet UIView *errorOverlay;
    IBOutlet UIButton *btnUsernameAccesary;
    
    int flag;
    BOOL isFrameExtended,isUsernameAutoGenerated;
    AppDelegate *appDelegate;
    UIImagePickerController * imagePicker;
}

- (IBAction)btnSelectImage:(id)sender;
- (IBAction)btnSignInAction:(id)sender;

@end
